---
- name: reload consul
  sudo: yes
  command: systemctl reload consul
  notify:
    - wait for consul to listen

- name: wait for consul to listen
  command: consul-wait-for-leader.sh

- name: reload consul-template
  sudo: yes
  command: systemctl reload consul-template
